#
# Stolen from AbnormalPoof's fork, didnt knew workflows existed lmao
#

# This is a basic workflow to help you get started with Actions

name: COMPILE ON WINDOWS

# Controls when the workflow will run
on:
  pull_request:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.0
      # Runs a set of commands using the runners shell
      - name: funny dependencies
        run: |
          haxelib install away3d
          haxelib install flxanimate 3.0.4
          haxelib install flixel-addons 2.10.0
          haxelib install flixel-tools 1.5.1
          haxelib install flixel-ui 2.5.0
          haxelib install flixel 5.2.2
          haxelib install lime 8.1.1
          haxelib install openfl 9.2.2
          haxelib install hscript 2.5.0
          haxelib install hxvlc 1.2.0
          haxelib install hxcpp 4.3.2
          haxelib git linc_luajit https://github.com/superpowers04/linc_luajit
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc.git
      - name: compilation
        run: |
          haxelib run lime build windows -dce no
          
      - uses: actions/upload-artifact@v2
        with:
          name: NightmareVision
          path: export/release/windows/bin
